version: '3'
services:
  web:
     build:
       context: .
       dockerfile: Dockerfile
    #  image: myweb:v1.0.1
     ports:
      - "8080:80"
     networks:
      - myweb-network 
     volumes:
      - myweb-vol:/usr/share/nginx/html  
volumes:
 myweb-vol:
networks:
 myweb-network: